### ISSUE TITLE
clean-webpack-plugin: /Users/user/.../ must be inside the project root. Skipping...

### ISSUE THREAD

**Issue by stianlp** [johnagan/clean-webpack-plugin#10]
I get this error after updating to 0.1.6.

If i revert to 0.1.4, it works fine. Is it possible to add an option to clean outside project root in the upcoming versions?

**Comment by rewmike** [comment]
I am having the same issue.

**Comment by chrisblossom** [comment]
@stianlp @rewmike Please provide your config so I can test

**Comment by fr-ench** [comment]
I am having the same issue as well. My project root is "z:/" , and I'm trying to delete 'dist' folder, which path is 'z:/dist'.
Reverting back to 0.1.4 fixes the issue.

**Comment by chrisblossom** [comment]
@fr-ench please provide your config.

**Comment by fr-ench** [comment]
@chrisblossom, here it is: 

var    Clean = require('clean-webpack-plugin');
...
 plugins: (function () {
        var plugins = [
            new Clean(["dist"], {
              root: 'z:/',
              verbose: true, 
             dry: false
          }),
            ....
       ];
       return plugins;
    })()
...

I've also tried root options as '/' but no help unfortunately.
I'm on windows and running node v5.5.0 if it can be helpful.

**Comment by hatchbee** [comment]
+1

**Comment by fr-ench** [comment]
@hatchbee , unfortunately, I'm still getting the same error: 
"clean-webpack-plugin: Z:\dist must be inside the project root. Skipping..."
with 
new Clean(["dist"], {
       root: process.cwd(),
       verbose: true, 
       dry: false
}).

**Comment by rewmike** [comment]
```
clean-webpack-plugin: /var/www/vhosts/[domain.com]/app project root is outside of project. Skipping all...
```

My webpack.config.js:

```js
new CleanPlugin(['build'], { root: __dirname })
```

My project structure:

```
.
├─ build
├─ source
└── webpack.config.js
```

I don't think that [`__dirname` should be used in `clean-webpack-plugin/index.js`][1] - it's not perfect.
[1]: https://github.com/johnagan/clean-webpack-plugin/blob/master/index.js#L66-L67

**Comment by hatchbee** [comment]
@fr-ench what is your ```process.cwd()``` and ```__dirname```?

Make sure you absolutely target the folder. I did tried a lot and what to bang my head but then tried ```root: process.cwd()```

I have this project structure:
```
--build-config/
 -----devConfig.js
--public/
-----dist/
```

The config below also worked for me:
```
plugins:[
         new CleanWebpackPlugin(['client/dist'], { root: path.resolve(__dirname , '..'), verbose: true })
      ]
```
And I am bundling with this command from my root of the project:
```
webpack --config build-config/dev.config.js  --watch
```

Make sure you give correct root path.

**Comment by fr-ench** [comment]
@hatchbee,

That doesn't help either.

Actually I believe the bug is on line 63:
var projectDirSplit = projectDir.split(path.sep);

I have projectDir = "z:/" which produces an array ["z:", ""]. There is an excessive empty array element "" in the end.

So we're getting an excessive check here

projectDirSplit.forEach((function(singleDir, index) {
      if (pathSplit[index] !== singleDir) {
        insideFailCheck = true;
      }
    }));

which results in insideFailCheck = true;

Probably your root variable doesn't end with a path separator, that is why it's working for you. But I use subst command to mount a "z:" drive and work from z:/ directly so just changing the plugin settings won't work for me.

**Comment by hatchbee** [comment]
@fr-ench just double check the way `path.resolve` works on Windows machine with drive paths. Sorry I haven't used it for development since.

**Comment by chrisblossom** [comment]
The tests are failing on windows. I am looking into a solution right now. Thanks for the input @fr-ench. 

Side note (haven't researched), is it possible for Travis-ci to test on windows hosts as well?

**Comment by chrisblossom** [comment]
@fr-ench can you try again with case-sensitive inputs including a capital Z:\? I think this is the issue.

**Comment by chrisblossom** [comment]
@fr-ench Can you try this branch: https://github.com/chrisblossom/clean-webpack-plugin/tree/feature/windows_fixes and see if your issues are fixed? Please advise.

**Comment by fr-ench** [comment]
@chrisblossom,

The windows_fixes branch works just perfect for me! Thank you! 
Do you think it'll make its way to master branch in the nearest future? 

As for case sensitivity, I don't think that was the case, because I tried different cominations at the very beginning.

**Comment by chrisblossom** [comment]
Thanks for testing it out. @fr-ench PR #14 submitted
