### ISSUE TITLE
How do I remove specific directories with v2?

### ISSUE THREAD

**Issue by StephanBijzitter** [johnagan/clean-webpack-plugin#109]
We have different builds for each supported language and the directory structure is as follows:

build/nl-NL/...files
builds/de-DE/...files
...etc

With the v1 config, it was easy to remove all builds, even if only building the Dutch build. However, with v2, the plugin now only removes build/nl-NL/ and leaves build/de-De/ as it is.

How can I replicate the same behaviour with V2?

### v1 Config

```js
new CleanWebpackPlugin([
    resolve('build'),
    resolve('debug'),
    resolve('bundlesize'),
], {
    allowExternal: true,
    verbose: true
});
```

### v2 Config (incomplete)

```js
new CleanWebpackPlugin({
    verbose: true
});
```

**Comment by chrisblossom** [comment]
I'm guessing `build/nl-NL/` is webpack's `output.path`. See the docs for `cleanOnceBeforeBuildPatterns` and `cleanAfterEveryBuildPatterns`.

```js
const { resolve } = require('path');

new CleanWebpackPlugin({
    cleanOnceBeforeBuildPatterns: [
        resolve('build/**/*'),
        resolve('debug/**/*'),
        resolve('bundlesize/**/*'),
    ],

    verbose: true,
    dry: true, // remove after testing
});
```

If you want to delete the directory itself not just the contents, remove the last `/*` from each pattern.

**Comment by StephanBijzitter** [comment]
Aaahhh, I must've misunderstood the docs for cleanOnceBeforeBuildPatterns, this is indeed what I need!

Thanks a lot!
