### ISSUE TITLE
Update README from 1.0.1

### ISSUE THREAD

**Issue by cnt000** [johnagan/clean-webpack-plugin#111]
### README seems to explain wrong configuration

I used 1.0.1 version but README is not correct.

Example:

**README** from master (github main page):

```
new CleanWebpackPlugin({
    // Simulate the removal of files
    //
    // default: false
    dry: true,
...........
})
```

**README** from ts branch:

`new CleanWebpackPlugin(paths [, {options}])` -> right one for 1.0.1

example: 

**README** from master: (https://github.com/johnagan/clean-webpack-plugin/blob/master/README.md)

```
    // Allow clean patterns outside of process.cwd()
    //
    // requires dry option to be explicitly set
    //
    // default: false
    dangerouslyAllowCleanPatternsOutsideProject: true,
```

**README** from ts branch: (https://github.com/johnagan/clean-webpack-plugin/blob/ts/README.md)

```
  // allow the plugin to clean folders outside of the webpack root.
  // Default: false - don't allow clean folder outside of the webpack root
  allowExternal: false
```

**Comment by chrisblossom** [comment]
The readme on master is for `v2`. Because `v1` is no longer supported, I would recommend upgrading to `v2`. See also: https://github.com/johnagan/clean-webpack-plugin/issues/106
