### ISSUE TITLE
Documentation example seems wrong

### ISSUE THREAD

**Issue by SetTrend** [johnagan/clean-webpack-plugin#114]
### Issue description or question

The sample code in `readme.md` reads (comments removed for brevity):

```js
const CleanWebpackPlugin = require('clean-webpack-plugin');

const webpackConfig = {
    plugins: [
        new CleanWebpackPlugin(),
    ],
};

module.exports = webpackConfig;
```
<br/>

I, however, have to write:

### Webpack Config

```js
const cleanWP = require('clean-webpack-plugin').default;

module.exports = {
  plugins: [
    new cleanWP()
  ]
};
```

... for Visual Studio Code (and the TypeScript compiler) to correctly construct `clean-webpack-plugin`.

**Please note the additional `.default` in the first line.**
<br/>

Shouldn't this additionally required `.default` be mentioned in the `readme.md` file?

### Environment

Run: `npx envinfo --system --binaries --npmPackages clean-webpack-plugin,webpack`

```bash
 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz
    Memory: 11.00 GB / 16.00 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
```

**Comment by johnagan** [comment]
Not sure it's required to include `.default` since the class is exported as default:
https://github.com/johnagan/clean-webpack-plugin/blob/master/src/clean-webpack-plugin.ts#L315

Are you getting errors without it?

**Comment by chrisblossom** [comment]
`.default` is not required because we use [`babel-plugin-add-module-exports`](https://github.com/johnagan/clean-webpack-plugin/blob/e90a300fdab0f36e671461bb2ccfbd93f288554c/.babelrc.js#L18-L26). As you have found out, VS Code / Typescript doesn't provide hints if you don't include `.default`. [See this thread for more information](https://github.com/facebook/jest/pull/7554#issuecomment-454358729).

I do not think the `readme` should be updated to include `.default` in the example for the sake of VS Code / type hints, but it might be possible to modify the types included to work with and without `.default`. @SimenB / @DanielRosenwasser did either of you ever figure out a solution to this?

**Comment by SimenB** [comment]
You can do `export =`, and intellisense should be happy. That's not really a good solution, though. Happy to learn otherwise!

**Comment by chrisblossom** [comment]
Thanks for the response @SimenB!

I'm not familiar enough with Typescript to understand the implications of switching to use `export =` in combination with `tsconfig.json`'s `"module": "commonjs"` setting. I know we'd need to use jest's [babel-plugin-jest-replace-ts-export-assignment.js](https://github.com/facebook/jest/blob/d792940b01ee1e17e435574e6cf4830b5186245e/scripts/babel-plugin-jest-replace-ts-export-assignment.js).

Looks like all we lose is the ability for someone to require `.default` and everyting else would work as expected? Wonder if Typescript type hints will work correctly if using `import cleanWebpackPlugin from 'clean-webpack-plugin';`

**Comment by chrisblossom** [comment]
After some testing, looks like unless `tsconfig.json` has `esModuleInterop": true`, the following error is thrown:

```js
webpack.config.ts:1:8 - error TS1192: Module '"/Users/chris/github/clean-webpack-plugin/dist/clean-webpack-plugin"' has no default export.

1 import CleanWebpackPlugin from 'clean-webpack-plugin';
         ~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by chrisblossom** [comment]
[From the docs](https://www.typescriptlang.org/docs/handbook/modules.html):
> When exporting a module using export =, TypeScript-specific import module = require("module") must be used to import the module.

Looks like without `"esModuleInterop": true`, `import CleanWebpackPlugin = require('clean-webpack-plugin');` works.

As of right now I'm not against the idea of migrating to use `export =`, but it is probably a breaking change. Thoughts? I'm not sure it is worth upping the version to `v3` for just this. Also, I would definitely prefer a less-hacky solution if anyone has any other ideas.

**Comment by SimenB** [comment]
Oh, this lib is written in TS, I thought it just had a `d.ts` file. Then I would _not_ change anything and just document the fact that consumers needs to add `.default` if their IDE/typechecker is yelling at them. The interop with CJS will always be a bit painful/ugly I think.

Jest will move to ES module exports in the next major and ditch `export =`.

One thing you can do is have a named export in addition to the default one, so people can do `const CleanPlugin = require('clean-webpack-plugin').plugin;` or something. Not much of a difference, but looks better than `default`, at least to my eyes

**Comment by chrisblossom** [comment]
#138 will resolve this issue.

**Comment by johnagan** [comment]
released with `v3.0.0`

**Comment by jinliming2** [comment]
Maybe it's not a good idea to just replace the default export with named export.

I think it's better to keep both named export and default export at the same time.

```javascript
export CleanWebpackPlugin;
export default CleanWebpackPlugin;
```

**Comment by chrisblossom** [comment]
@jinliming2 I wish there were a better way for common js and modules to work. I personally think dropping the default export is the best solution and I don't see us reverting that change.

If you'd like to rename the named export, you can do so:

```js
// es modules variable named "CleanPlugin"
import { CleanWebpackPlugin as CleanPlugin } from 'clean-webpack-plugin';

// common js variable named "CleanPlugin"
const { CleanWebpackPlugin: CleanPlugin } = require('clean-webpack-plugin');
```
