### ISSUE TITLE
dist folder will be clear while devServer started by execute 'npm run start'

### ISSUE THREAD

**Issue by penggle** [johnagan/clean-webpack-plugin#117]
### Issue description or question

dist folder will be clear while devServer started by execute 'npm run start'

### Webpack Config

```js
// paste your webpack config here
```

### Environment

Run: `npx envinfo --system --binaries --npmPackages clean-webpack-plugin,webpack`

```bash
# Paste the result here
```

**Comment by chrisblossom** [comment]
Please provide the following information:

- What exactly is happening?
- What do you expect to happen?
- Current webpack configuration.
