### ISSUE TITLE
Add an option to clean() only one time at start/init (inside watch-mode)

### ISSUE THREAD

**Issue by crazyx13th** [johnagan/clean-webpack-plugin#125]
Hey there,

would be nice to have this option to clean up  `only on start` my dev-server or `every x-times`.
Reason is that cleaning up my folders takes 0.5 - 1.0 sec :-)
thx!

Greetings
crazyx13th

**Comment by chrisblossom** [comment]
It is already an [option](https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional):

```js
new CleanWebpackPlugin({
    cleanStaleWebpackAssets: false,
});
```

**Comment by EgoPingvina** [comment]
Will this option work correct in prod mode, or I should create two different options of the plugin for each build mode?
