### ISSUE TITLE
V2 dist folder content is deleted before webpack start building

### ISSUE THREAD

**Issue by jimblue** [johnagan/clean-webpack-plugin#133]
### Issue description or question

Hi,

I've read the doc and a bunch of closed issue about this, but I didn't get how to replicate **beforeEmit** of V1?

Just need to stop removing all assets before webpack even start to bundle them...

Thank you so much for you help.

Cheers

### Webpack Config

```js
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
    plugins: [
        new CleanWebpackPlugin()
    ],
};
```

### Environment

```bash
System:
    OS: macOS Mojave 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 14.43 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
```

**Comment by chrisblossom** [comment]
I must say I am confused about [how `beforeEmit` worked previously](https://github.com/johnagan/clean-webpack-plugin/blob/v1.0.1/index.js#L190-L213). It is my understanding that the [`compile hook`](https://github.com/johnagan/clean-webpack-plugin/blob/9f8a3bb1843dad7e67c65173b014e208dfc75e22/src/clean-webpack-plugin.ts#L174-L184) happens [before the `emit` hook](https://webpack.js.org/api/compiler-hooks/), so to me they are accomplishing the same thing, unless you are wanting to clean after the `compile` hook. In that case, you should be able to use [`cleanAfterEveryBuildPatterns`](https://github.com/johnagan/clean-webpack-plugin/blob/9f8a3bb1843dad7e67c65173b014e208dfc75e22/src/clean-webpack-plugin.ts#L186-L193).

I wouldn't be against the idea of adding a custom hook option, but I'd like to understand the use case for this first. Is it possible for you to provide a minimal example to show what issue you are running into?

**Comment by jimblue** [comment]
Ok, let say my app is working well on prod and I have new version of the app to build and push.
If I launch webpack build and it fails, the dist folder will be empty my app will be broken.
A better solution would be to wait for build success before removing dist folder content.
That way the new build will replace the removed one and the app will never be broken in case the build add an error...

**Comment by chrisblossom** [comment]
Thanks for the explanation, it makes a lot of sense and we already do this for [`cleanAfterEveryBuildPatterns`](https://github.com/johnagan/clean-webpack-plugin/blob/9f8a3bb1843dad7e67c65173b014e208dfc75e22/src/clean-webpack-plugin.ts#L218-L227).

Any thoughts of why we wouldn't always use the `emit` hook over `compile`?

**Comment by chrisblossom** [comment]
@jimblue See #134

**Comment by jimblue** [comment]
Nice!!!! That was fast... thank you

**Comment by rohit-smpx** [comment]
When can we expect a release for this?

**Comment by johnagan** [comment]
done https://www.npmjs.com/package/clean-webpack-plugin

**Comment by jimblue** [comment]
Thanks @johnagan, it's working great now !
