### ISSUE TITLE
Add emitted flag checking, before directory removing

### ISSUE THREAD

**Issue by pawojciechowski** [johnagan/clean-webpack-plugin#15]
When error occur in webpack compilation and we're using NoErrorsPlugin(), there are no bundles emitted, but directory is removed. Maybe you can add any check of emitted to your plugin, so when no files are generated old ones still stay in place.

**Comment by johnagan** [comment]
Wouldn't this leave a misrepresented version of the build though? Seems that if the build is broken, then there shouldn't be a working build sitting there.

**Comment by pawojciechowski** [comment]
Ok, that's good point of view. I simply don't like removing anything, if it isn't necessary. Thanks for replying back :)

**Comment by johnagan** [comment]
> Thanks for replying back :)

No worries :sunglasses:
