### ISSUE TITLE
Files written to disk removed after save

### ISSUE THREAD

**Issue by coreyworrell** [johnagan/clean-webpack-plugin#154]
When using `devServer.writeToDisk: true`, files are written to disk correctly, but after saving a file and Webpack compiles again, those files are not on disk anymore.

### Webpack Config

```js
{
  devServer: {
    writeToDisk: true
  },
  plugins: [
    new CleanWebpackPlugin
  ]
}
```

**Comment by chrisblossom** [comment]
Please post your full configuration. Try:

```js
new CleanWebpackPlugin({
	cleanStaleWebpackAssets: false
})
```

**Comment by coreyworrell** [comment]
That seems to fix it. Not sure if there are any side effects, or why Webpack now thinks those assets are stale, as this seems to have only started after updating to latest versions of Webpack and plugin.

**Comment by coreyworrell** [comment]
I found another thread that mentioned using the `cleanAfterEveryBuildPatterns`, so I will use that instead since I am only concerned with it losing `svg` files for now.

**Comment by chrisblossom** [comment]
I've attempted to [put a PR for `copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin/pull/360) but it has stalled waiting for input.

`cleanAfterEveryBuildPatterns: ['!**/*.svg']` should work great if that is all you need to ignore.

**Comment by coreyworrell** [comment]
Okay perfect, hopefully that gets some traction over there soon. Appreciate the help!

**Comment by chrisblossom** [comment]
Going to close this. Please open a new issue if you have anymore issues.
