### ISSUE TITLE
Support to specify exclude files/directories

### ISSUE THREAD

**Issue by Danita** [johnagan/clean-webpack-plugin#16]
In my project I usually check in version control the `/dist` directory in order for it to be ready for deploy without the need for installing dependencies and running the build step. In that directory should also reside a `config.js` file with project configurations that varies from installation to installation. It would be nice to preserve that file between project rebuilds. Is there any support for this?

Thanks!

**Comment by chrisblossom** [comment]
I do not think this is currently possible. You might want to look into [sindresorhus/del](https://github.com/sindresorhus/del) (supports globs/exclusions). Also you could consider storing configuration in environmental variables. [motdotla/dotenv](https://github.com/motdotla/dotenv) works great for this purpose. See [http://12factor.net/config](http://12factor.net/config) for more information.

Hope this helps.

**Comment by johnagan** [comment]
> Also you could consider storing configuration in environmental variables. 

I agree with this :+1:
