### ISSUE TITLE
Support for MultiCompiler?

### ISSUE THREAD

**Issue by apfelbox** [johnagan/clean-webpack-plugin#161]
Hi,

webpack supports [`MultiCompiler`s](https://github.com/webpack/webpack/tree/master/examples/multi-compiler):

```js
webpack([config1, config2, ...]);
```

It seems that this plugin doesn't support it, as one of the compilers (the latest one) always removes the files from the previous builds..

Is this something that is on the roadmap / can be fixed?

**Comment by chrisblossom** [comment]
Multi-compilers are supported, you just need to setup your build correctly.

See https://github.com/johnagan/clean-webpack-plugin/issues/157#issuecomment-518347683 and linked issues.

**Comment by apfelbox** [comment]
All right, thank you @chrisblossom !
