### ISSUE TITLE
remove cached assets on rebuild

### ISSUE THREAD

**Issue by Viktor-the-great** [johnagan/clean-webpack-plugin#162]
[On this code line](https://github.com/johnagan/clean-webpack-plugin/blob/master/src/clean-webpack-plugin.ts#L260) fetch only emitted assets. 

For this reason I can not use 'cache' option of HtmlWebpackPlugin (removes index.html on rebuild).

_What about to pass 'cachedAssets' option to toJson method to fetch cached assets?_

**Comment by chrisblossom** [comment]
I am unsure what you mean about a `cachedAssets` option.

You either need to set `cleanStaleWebpackAssets: false` or add negative patterns to `cleanAfterEveryBuildPatterns: ['!index.html']`.

**Comment by chrisblossom** [comment]
Going to close this. Please reopen if you are still having an issue.
