### ISSUE TITLE
Error: "project root is outside of project"

### ISSUE THREAD

**Issue by alextreppass** [johnagan/clean-webpack-plugin#17]
Hi, 

Due to various reasons in our project, the client builds into the 'public' folder of our rails app. For illustration purposes:
- `server/client` - client dir (where `webpack.config.js` lives), and where the build is run from
- `server/public` - webpack `config.output.path` dir, where webpack builds relative to

It looks like this plugin relies on `workingDir` (i.e. `process.cwd()`) over webpack's `config.output.path`.

Would it be ok to change this? Webpack is building happily into a folder that isn't the cwd.

What I'm looking for is to remove / clean the files pre-build, in:
- `server/public/scripts` and `server/public/styles`
- leave anything else in `server/public` intact

Thanks!

**Comment by johnagan** [comment]
@alextreppass I'm no opposed to it. Is it something you can propose in a PR?

**Comment by chrisblossom** [comment]
@alextreppass You do not need to change anything. ```process.cwd()``` is the safe default for the ```root``` option.

```js
var CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
  plugins: [
    new CleanWebpackPlugin(['dist', 'build'], {
      root: '/full/project/path/server/public',
      verbose: true, 
      dry: false
    })
  ]
}
```

**Comment by alextreppass** [comment]
I'll give it a go, thanks!

**Comment by alextreppass** [comment]
Hmm still running into that issue I'm afraid.

Here's my config:
```javascript
 new CleanWebpackPlugin(['scripts', 'styles'], {
    root: TARGET_DIR,
    verbose: true,
    dry: false
  }),
```

- `TARGET_DIR` is something like `/path/to/server/public`. This is webpack's `config.output.path` dir.

- `process.cwd()` (from where I'm running webpack) is `/path/to/server/client`

**Comment by chrisblossom** [comment]
@alextreppass Could you provide a failing test case? [test/test.js](https://github.com/johnagan/clean-webpack-plugin/blob/master/test/tests.js)

**Comment by chrisblossom** [comment]
I believe this is showing the issue:
```js
    it('root outside of process.cwd()', function () {
      var outsideProjectDirOne = '/test/dir/_one';
      // outsideProjectDir === '/test/dir'
      cleanWebpackPlugin =
        new CleanWebpackPlugin([outsideProjectDirOne], { root: outsideProjectDir, dry: true });
      result = cleanWebpackPlugin.apply();

      expect(result[0].output).to.equal('removed');
    });
```
[index.js#L89](https://github.com/johnagan/clean-webpack-plugin/blob/master/index.js#L89) is where the check is failing.
I think adding your suggestion to check config.output.path on the failing path is a good idea. Might also be a good idea to add an option to skip that check for other edge use cases.

**Comment by alextreppass** [comment]
Here's a diff where I've got it working for my needs: https://github.com/alextreppass/clean-webpack-plugin/commit/a098e7654da834ff32d5e7452d63863807f9acdd

It doesn't seem that webpack exposes wider config (like `output.path`) to plugins, so I re-worked it to only block cleaning out folders that are outside of the `root` clean-webpack-plugin config.

I'm seeing if I can tweak the tests now.

**Comment by alextreppass** [comment]
Ok got a bit further, I've added some new dirs in `index_spec.js` to explain my use-case.

The OSX tests pass now, but the windows one blow up: https://github.com/johnagan/clean-webpack-plugin/pull/18

**Comment by chrisblossom** [comment]
I don't think removing all of the safety checks is a good solution. Try my latest branch https://github.com/chrisblossom/clean-webpack-plugin

**Comment by alextreppass** [comment]
Got the tests passing in #18 - I had missed the `windows_spec.js` file, whoops.

I think I removed only the checks that were ensuring the root was under the project dir, and ensured that any dirs to be deleted must be under the given 'root' dir (unrelated to the project / working dir).

**Comment by alextreppass** [comment]
Nice, your approach works also, just tested it here locally. 👍 

I guess the question for your consideration is: do we tie it implicitly to webpack (this is probably fine, it's a webpack plugin after all!), or do we change the semantics about 'projectDir' vs 'rootDir'.

I'd be happy with either :)

**Comment by chrisblossom** [comment]
Just checking to make sure the files being deleted is inside of ```root``` does simplify the plugin. Also it wouldn't break with any Webpack API changes.

Also, I don't think it would break anyone's current config. Thoughts? Only downside I can think of it potentially makes the plugin less "safe" from deleting files/directories by mistake.

**Comment by alextreppass** [comment]
Yeah I guess it might be more portable -- do webpack document the `compiler.options` in-scope? If they changed how that's exposed we'd still be fine.

I googled around a bit for `compiler.options` and it seems webpack-dev-server might not have an `output` path, so sniffing output might not work for that case. [[1](https://github.com/webpack/webpack/issues/1563#issuecomment-156748183)]

Semantics - yeah I agree it'd be compatible with current config, we're still telling the plugin `"under this root folder, please delete this folder (or these folders)"`.

I agree the potential danger is the main concern. As you say, what if the user mistakenly puts in a root value that they shouldn't?

How about a new config option like `allowExternalRoot`, which is `false` by default? They'd have to look in the README and opt-in to using it

**Comment by chrisblossom** [comment]
I am happy with removing the process.cwd()/running directory check as long as absolute root paths for ```root``` is still enforced. Seems like most rounded solution to me.

**Comment by alextreppass** [comment]
@johnagan - are you ok with #18 as a solution to this?

**Comment by johnagan** [comment]
@alextreppass I'd want @chrisblossom's sign-off too because some of this is his code too.

**Comment by chrisblossom** [comment]
I created a PR@https://github.com/alextreppass/clean-webpack-plugin/pull/1 for @alextreppass to look over. Everything looks good to me outside of that.

**Comment by alextreppass** [comment]
Hey thanks, I'll integrate this into #18

**Comment by ervoiox** [comment]
Any updates? Could really use this.

**Comment by alextreppass** [comment]
@chrisblossom / @johnagan - I merged Chris' code into my branch; #18 is ready to go if you guys are happy.

Thanks!

**Comment by chrisblossom** [comment]
Looks good to me.

**Comment by johnagan** [comment]
Deployed [v0.1.9 to npm](https://www.npmjs.com/package/clean-webpack-plugin).

Thanks everyone 👍

**Comment by alextreppass** [comment]
Cheers 👍

**Comment by pmunin** [comment]
Does not for work projects with multiple workspaces, where there is some webpack.config.base.js injecting clean-webpack-plugin in it located in another folder outside the subpackage
