### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by Viktor-the-great** [johnagan/clean-webpack-plugin#170]

**Comment by chrisblossom** [comment]
The changelog is handled via [Github releases](https://github.com/johnagan/clean-webpack-plugin/releases).

**Comment by davidspiess** [comment]
@chrisblossom what changed in v4? there is no information about breaking changes.

**Comment by pataar** [comment]
Looking at the commits, it seems it's like this:

- Removed Node 8 support
- Removed Webpack 3 support
