### ISSUE TITLE
Cannot install module on windows 10

### ISSUE THREAD

**Issue by ArtemZag** [johnagan/clean-webpack-plugin#19]
When I install this module on windows 10 I get error:

`> npm install --save clean-webpack-plugin
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN react-addons-pure-render-mixin@15.0.2 requires a peer of react@^15.0.2 but none was installed.
npm WARN react-addons-shallow-compare@15.0.2 requires a peer of react@^15.0.2 but none was installed.
npm WARN react-workshop@1.0.0 No repository field.`

**Comment by johnagan** [comment]
@ArtemZag have you read through this? https://github.com/npm/npm/issues/9204#issuecomment-216853959

**Comment by ArtemZag** [comment]
No. I didn't. Thanks.
