### ISSUE TITLE
v4.0.0-alpha.0 is released as `latest`

### ISSUE THREAD

**Issue by mariuslundgard** [johnagan/clean-webpack-plugin#199]
### Issue description or question

Since v4.0.0-alpha.0 is tagged as `latest` on npm, there’s a mental burden when updating projects.

`yarn outdated` will show that the package needs an update, while it’s not desirable to upgrade to an alpha version (in my case at least).

![image](https://user-images.githubusercontent.com/406933/114676669-cd537f80-9d09-11eb-859f-82400ee151e3.png)

**Comment by grahamb** [comment]
This is still an issue. Why is the alpha version being advertised as `@latest`?

**Comment by silkfire** [comment]
@chrisblossom @johnagan Agreed, and is there a release plan for v4.0.0? The last release was more than two years ago.

**Comment by Agent-Jones** [comment]
Any news on this?

**Comment by grahamb** [comment]
What are the breaking changes in this release? There's no changelog or [release notes](https://github.com/johnagan/clean-webpack-plugin/releases/tag/v4.0.0).

**Comment by baywet** [comment]
looking at [the diff](https://github.com/johnagan/clean-webpack-plugin/compare/v3.0.0...v4.0.0) I think the answer is:

# Breaking changes:
- Dropped support for NodeJS 8
- Dropped support for webpack 3

# Changes
- Added support for NodeJS 14
- Added support for webpack 5
