### ISSUE TITLE
Clean problem

### ISSUE THREAD

**Issue by binjospookie** [johnagan/clean-webpack-plugin#20]
After recompiling(hot reload + watch) in my project folder i see old .css and .js files(i use [cahe] for them) and new files. What should i do to delete old files on hot reload?

My config file:
https://jsfiddle.net/9rmt24yp/1/

And what i see in directory on hot reload:
https://i.gyazo.com/95db01780779f041f0596c134075e04b.png

**Comment by Shepless** [comment]
Also seeing this. Apologies of this is obvious but I'm very new to webpack.

**Comment by binjospookie** [comment]
@Shepless 
I resolved this problem by adding hash only for production version. In development files will be rewrite.

**Comment by Shepless** [comment]
@binjospookie Simple solutions are often the best! Thanks for sharing!

**Comment by johnagan** [comment]
Can we close this one or is there still an open bug?

**Comment by TombolaShepless** [comment]
@johnagan It can be closed from my perspective...

**Comment by johnagan** [comment]
Awesome! Thanks folks ✨

**Comment by dxcqcv** [comment]
so is there no way to clean folder in watch method ? can add a feature to clean on the watch method?
