### ISSUE TITLE
Possible to prevent downtime while deploying?

### ISSUE THREAD

**Issue by sungwoncho** [johnagan/clean-webpack-plugin#22]
When deploying, my server pulls from the remote, and compiles a fresh build. I am using `clean-webpack-plugin` to clean up old build.

However, `clean-webpack-plugin` cleans the previous build at the start of the new build, and until the build is done, none of the assets will be accessible. Is it possible to delay clean up to prevent this downtime?

Also related is https://github.com/erikras/react-redux-universal-hot-example/issues/1093

**Comment by johnagan** [comment]
There isn't the concept of staging assets for the project right now. If you get the itch, you're welcome to make a pass at adding one and submitting a PR. I'm not sure how difficult it would be though 😕

**Comment by sungwoncho** [comment]
@johnagan I think this feature is nice to have, but is beyond the scope of a webpack plugin. I simply wrote a shell script to be run after a webpack build. Closing this.

For anyone in a similar situation, here is the script: https://gist.github.com/sungwoncho/9d3301d41a54c4643b85690e1266d373

**Comment by milewski** [comment]
this has being fixed by adding this option: `beforeEmit: true`
