### ISSUE TITLE
This plugin time starts webpack build effective only, watch the process does not work

### ISSUE THREAD

**Issue by Mmzer** [johnagan/clean-webpack-plugin#25]

**Comment by tylerhou** [comment]
This issue can't be fixed given the current architecture of the plugin. I wrapped the former .apply() function inside an event listener in my pull request which fixes this issue, but it has the added side effect of failing every test because of the changed architecture. We'd have to also restructure how tests are done too.

**Comment by rawberg** [comment]
just noticed it doesn't work with watch, files start to pile up. this would be a nice addition!

**Comment by TSMMark** [comment]
this is very important feature.

**Comment by kingjerod** [comment]
This is really a deal breaker for me. For anybody else who finds this issue, clear old files on watch is supported in this plugin: https://github.com/gpbl/webpack-cleanup-plugin

**Comment by johnagan** [comment]
@kingjerod all PRs are welcome

**Comment by kingjerod** [comment]
@tylerhou said:
> This issue can't be fixed given the current architecture of the plugin.

Based on that, looks like it would be close to a full re-write?

**Comment by tylerhou** [comment]
Ignore that. I may have been talking out of my ass.

**Comment by tylerhou** [comment]
Also, @johnagan, there have been two pull requests which fix this issue: #32 and #35, respectively, which have been open for 5 months and 4 months respectively. The first one I wrote; it plays well with the current tests but I didn't add tests for the --watch option; the second one is fully tested but (according to the author) has bugs.

If tests are really really necessary for you, then please tell me and I'll take another look at the code. If you want to do any code review, I'm happy to work with you. All pull requests might be welcome, but it doesn't seem like you're a fan of giving feedback or of pulling them.

**Comment by johnagan** [comment]
@tylerhou I think it was your recommendation to wait for the other with tests
https://github.com/johnagan/clean-webpack-plugin/pull/32#issuecomment-281882026

That PR isn't mergable though

**Comment by johnagan** [comment]
https://github.com/johnagan/clean-webpack-plugin/pull/35#issuecomment-273233989

**Comment by tylerhou** [comment]
I was just letting you know that the other PR had tests, and you might want to pull that one instead. But if it's inherently buggy, as the author claims, that's an entirely different issue altogether.

My PR also was definitely mergeable when I submitted it five months ago, and it's not too difficult to resolve the merge conflicts. I just did.

**Comment by johnagan** [comment]
I'm happy to pull in a PR right now. If you think this is GTG as is, I'm 👍

**Comment by tylerhou** [comment]
It's GTG if you're willing to accept that it has no tests for the watch function. I'm not sure how to write them.

**Comment by johnagan** [comment]
me either. I'll pull it in. worse case we just revert it... again 😏

**Comment by tylerhou** [comment]
Yeah, my bad on that first time. My first legit pull request.

**Comment by johnagan** [comment]
`0.1.16` pushed to npm
