### ISSUE TITLE
Prevent auto run when call webpack()

### ISSUE THREAD

**Issue by agusputra** [johnagan/clean-webpack-plugin#29]
It seems this plugin auto run when we call `webpack(options)`. 

How to to configure this plugin to not auto run ?

ex:
```
//This plugin auto run and the directory now clean after call webpack(). But I don't want it.
compiler = webpack(options);

//How to configure this plugin, so it run when compiler.run() called?
compiler.run()
```

**Comment by hustcer** [comment]
I have the same issue here at v0.1.12, it just don't clean as before: I want it to clean the directory when I first run the task like `npm run dev`, then after any later file changes, the directory need not be cleaned, It's just an incremental build, not a full build. At least it should be configurable.

**Comment by johnagan** [comment]
@tylerhou this seems to be a result of your PR #25. Should I roll this back?

**Comment by johnagan** [comment]
I rolled back #30 until it's resolved

**Comment by tylerhou** [comment]
Sorry about that. I didn't realize that it would run there too. Perhaps the best solution is to have an option `watch (default: false)` which would attach the event listener if true.

**Comment by tylerhou** [comment]
On closer inspection, this isn't a problem with the pull request I made. Here's a repo of the bug at `v0.1.13`:

```
var CleanWebpackPlugin = require('clean-webpack-plugin');
var webpack = require("webpack");

// returns a Compiler instance
var compiler = webpack({
  plugins: [
    new CleanWebpackPlugin(['dist'])
  ]
});
```

`$ node index.js`
`dist` gets deleted.

@hustcer your bug isn't the same; it's a duplicate of #29. #29 is also incorrect in referencing this bug as the two are not linked.
