### ISSUE TITLE
Skip deletion of the assets from the few previous builds

### ISSUE THREAD

**Issue by dmitry** [johnagan/clean-webpack-plugin#3]
Should not delete an bundled assets from the few previous builds.

In my opinion there should be two options:

- number of previous builds to keep
- number of hours or days

Similar thing is done on rails/sprockets: https://github.com/sstephenson/sprockets/blob/777f1ebfcbb397479d28509bce2ac67d12d40320/lib/sprockets/manifest.rb#L252

**Comment by johnagan** [comment]
> In my opinion there should be two options:
>
> number of previous builds to keep
> number of hours or days

While I appreciate the suggestion, I'm not sure I agree. I modeled this after gulp-clean, rather than sprockets.

IMO I think your scenario requires another plugin that runs before this one that will version it.

**Comment by dmitry** [comment]
@johnagan how do you think it should version a built assets?

**Comment by johnagan** [comment]
> @johnagan how do you think another plugin should version a built assets? 

I don't. I want it to wipe the folder every build

> Isn't you trap into the scenarion, when you are deploying an application, and the old users are still could get an assets from the old build?

Nope. The point would be to exclude compiled assets from GitHub / versioning. It sounds like you're using your build directory as your distribution directory.

**Comment by dmitry** [comment]
@johnagan your approach is to push built assets into the github, and then deploy to a production server. Lets imagine that you've deployed a SPA application first time to the server, user got your application and started to browse. Your assets has a links to a URL in the javascript, and loading on demand (through the webpack async loader) when user tries to access additional resources (let`s think it's homepage to search) before you deployed the next version of your application, when your application used `[hash]` for defining the filename urls, instead of `[chunkhash]` or you've changed contents of the assets (some of the icons were optimized). Because you are cleaning the build path, everything will be cleaned up and user will get a 404 error in this case.
What I suggest - to leave files at least for a couple of hours after the deployment, or to leave them for a few releases more, before the users will receive an updated JS with a new links to an assets.

**Comment by johnagan** [comment]
@dmitry you're welcome to open a pull request with your recommendation and I'll review it.
