### ISSUE TITLE
Plugin doesn't seem to run.. are there further install steps?

### ISSUE THREAD

**Issue by ptim** [johnagan/clean-webpack-plugin#4]
Hi, 
I have npm installed, and instantiated Clean in my config, and my 'compile' task runs without errors, but I don't see stale files being deleted... Any tips?

Config snippet:
```
webpackConfig.plugins.push(
  new Clean(['dist']),
  new ExtractTextPlugin('[name].[contenthash].css', {allChunks: true})
);
```

**Comment by lenards** [comment]
@ptim - do you the full config or a link to the project? I'm down to try to reproduce this.

**Comment by ptim** [comment]
hi @lenards! I'm using the https://github.com/davezuko/react-redux-starter-kit as a base - I'll create a branch on my fork and see if I can repro it there.. tx! 

(it may be an issue with the kit - I can't get the other webpack clean plugin to run either)

**Comment by johnagan** [comment]
> (it may be an issue with the kit - I can't get the other webpack clean plugin to run either)

@ptim That's my guess. I'm not familiar with that kit
