### ISSUE TITLE
Proposal for a v2.0 in ES6

### ISSUE THREAD

**Issue by johnagan** [johnagan/clean-webpack-plugin#40]
👋  Hello everyone. Thank you for ongoing support of this project. It's been a while since I used webpack, but now that I'm coming back into it, I would love to modernize this project. Ideally in ES6 and not one massive file 😎 

Since I haven't used it recently, I'd love some feedback on if we should do this and what it needs.

**Comment by mikedpad** [comment]
Hey @johnagan, thanks for your contribution to the webpack community.

Just my opinion, but I'd like to be able to wrap the paths AND options into a single object, just for the sake of readability. Not unlike `extract-text-webpack-plugin` changes from v1 to v2 where `filename` is now passed via an object and not a separate parameter.

For instance, as it stands right now:
```
new CleanWebpackPlugin(['build'], {
  root: path.resolve(__dirname),
  verbose: true,
})
```

To just a single object:
```
new CleanWebpackPlugin({
  paths: ['build'],
  root: path.resolve(__dirname),
  verbose: true,
})
```

Just my two cents. Cheers 🍻

**Comment by Nargonath** [comment]
Hello! Yeah thanks for your contribution to the webpack ecosystem. I would be happy to help on refactoring the plugin in ES2015. I haven't really looked into the project yet but I'll try to dive in a bit more and I'll see if I can give some propositons as of how to refactor it. :)

**Comment by Nargonath** [comment]
At first glance, one thing I see is that we could create a `utils.js` or something like that and we'd put the helper functions `isAbsolute` and `upperCaseWindowsRoot` to remove them from the main file.

**Comment by johnagan** [comment]
Moving to the WIP PR #47
