### ISSUE TITLE
Possible to exclude folders in addition to files?

### ISSUE THREAD

**Issue by scott-thrillist** [johnagan/clean-webpack-plugin#41]
I want to delete all files in /build/ except everything in /build/vendor

```
new CleanWebpackPlugin([
    `${config.dist}*`  // user builds
], {
    exclude: ['vendor/']
}),
```

Is something like this possible yet?

**Comment by scott-thrillist** [comment]
Found a way to accomplish what I wanted:

```
new CleanWebpackPlugin([
    `${config.dist}*.*`  // will only delete files like so /build/*.* 
]),
```

This will leave /build/vendor alone but it would still be nice if an item in the include array didn't have an extension it would be treated as a directory to exclude. If this is the consensus and no one else has the time to look into this I can add it when I have free time.

**Comment by zdanowiczkonrad** [comment]
Yes, there already is such an option - `exclude` property, exactly like you wrote in the original question, but please try without the trailing slash.

**Comment by mtness** [comment]
None of the tip above worked for me so far -
but a look at the example in the readme file gave me the clue -
it seems i cannot exlude folders, but regex-filenames.

`    // Use !negative patterns to exclude files
    //
    // default: ['**/*']
    cleanOnceBeforeBuildPatterns: ['**/*', '!static-files*'],`
