### ISSUE TITLE
Small docs update suggestions

### ISSUE THREAD

**Issue by stephen-last** [johnagan/clean-webpack-plugin#42]
For paths, maybe add a couple more examples, including how to remove the contents of the folder, rather than the folder itself:

```js
[
  'dist',      // removes 'dist' folder
  'build/*.*', // removes all files in 'build' folder
  'web/*.js'   // removes all JavaScript files in 'web' folder
]
```

For the root option, make it clear that it's the root of your package. The `webpack.config` file currently mentioned could actually sit anywhere, it doesn't have to sit in your package root folder (mine is in `/webpack/index.js`). 

```js
{
  root: __dirname // absolute path - your package root folder (paths appended to this)
}
```

I guess you could change `webpack.config` to `package.json`.

**Comment by johnagan** [comment]
done. thank you!
