### ISSUE TITLE
With 'watch' option enabled ALL chunks are removed after each new compilation

### ISSUE THREAD

**Issue by GProst** [johnagan/clean-webpack-plugin#43]
I wanted to try this new `watch` option, but it doesn't act as I expected.

When using `webpack --watch` with this option enabled **ALL** of the previously created chunks are removed after new compilation.

I am using `CommonsChunkPlugin` in order to apply [long-term cache support](https://webpack.js.org/guides/caching/). So when I use `webpack --watch` not all of my chunks are updated, but only those, which were affected by the last changes.

So I expected for `clean-webpack-plugin` to remove only **obsolete** chunks. 

This would be very nice, cause I will be able to use webpack watch mode along with `karma` watch mode.

The problem is that I use `[name].[chunkhash].js` pattern for my app.js chunk (and others). So at the moment it is not very efficiently to use `karma` watch mode along with `webpack` watch mode, `karma` will include all my chunks (old and new), because it uses `app*.js` pattern for files to include in it's config.

I suppose this issue is related to [this PR](https://github.com/johnagan/clean-webpack-plugin/pull/32)

**Comment by GProst** [comment]
OK, I actually think that this issue has nothing to do with this plugin. I think the feature I describe should be implemented in a separate plugin.

**Comment by simonsmith** [comment]
I've bumped into this exact issue. It would be ideal if `watch: true` could only clean the files that were effected by the change.

**Comment by GProst** [comment]
@simonsmith for this purpose you can use my plugin https://github.com/GProst/webpack-clean-obsolete-chunks

**Comment by simonsmith** [comment]
@GProst I literally just found that! It works perfectly. Thanks!
