### ISSUE TITLE
Feature request: clean from outside of the project root as well.

### ISSUE THREAD

**Issue by rbatllet** [johnagan/clean-webpack-plugin#45]
My target build is outside the project root and the previous build can not be cleaned (it's skipped). Please add an option to force to clean the target folder.

**Comment by damianobarbati** [comment]
+1 having same problem, wasn't this fixed? 

`new CleanPlugin(['../build'], { root: `${__dirname}/../`, verbose: true, watch: true }),`
=>
`clean-webpack-plugin: /Users/damiano/Desktop/build is outside of the project root. Skipping...`

**Comment by chrisblossom** [comment]
Please provide more information on how you are trying to clean outside the "target folder"?

See:
[tests.js#L61-L67](https://github.com/johnagan/clean-webpack-plugin/blob/bdfdcb351749bfb74533824049b6e6798fb03f6e/test/tests.js#L61-L67)
https://github.com/johnagan/clean-webpack-plugin/issues/17
https://github.com/johnagan/clean-webpack-plugin/pull/18

**Comment by rbatllet** [comment]
Here it is:

```
const targetPath = '../test-webapp/src/main/resources/public/frontend';

module.exports = function() {
  return webpackMerge(commonConfig, {
    ...
    plugins: [
      new CleanWebpackPlugin(['dist', targetPath], {
        root: process.cwd()
      })
    ],
  });
};
```

**Comment by rbatllet** [comment]
It does work:

```
const basePath = __dirname;
const targetPath = '../test-webapp/src/main/resources/public/frontend';
const targetFolder = 'dist';

module.exports = function() {
  return webpackMerge(commonConfig, {
    ...
    plugins: [
      new CleanWebpackPlugin([targetFolder], {
        root: basePath + '/' + targetPath
      })
    ],
  });
};
```
Thank you!
