### ISSUE TITLE
Exclude `.travis.yml` from package

### ISSUE THREAD

**Issue by evilebottnawi** [johnagan/clean-webpack-plugin#46]
This file don't need in package. It is reduce some package size :smile:

**Comment by michalkrupa** [comment]
^ it does, it is necessary for Travis CI to know what to build/how to test the package.

**Comment by evilebottnawi** [comment]
@michalkrupa from `npm publish`, we don't need `.travis.yml` as package in  node_modules

**Comment by michalkrupa** [comment]
Ah you mean for the published package - I misunderstood and thought you were referring to the repo. https://github.com/johnagan/clean-webpack-plugin/pull/51

**Comment by evilebottnawi** [comment]
@michalkrupa :smile:

**Comment by johnagan** [comment]
fixed with #51
