### ISSUE TITLE
does it work with webpack2?

### ISSUE THREAD

**Issue by t0lkman** [johnagan/clean-webpack-plugin#49]
for me it seems like it doesn't do anything..

**Comment by michalkrupa** [comment]
It does work, yes. Make sure that you are passing the root of your project into the plugin options - https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional

In my project the webpack config is in a subdirectory of the main project and the clean plugin does not process anything above that folder level unless the root option is explicitly set.

You can also get more information on what the particular issue in your environment may be by setting the ```verbose``` option as true as well - you will receive a message in the console if your error is the one I described. Hope this helps!

**Comment by KostiaGontarev** [comment]
Have the same issue, all options set. In verbose mode doesn't write anything to console.
