### ISSUE TITLE
the plugin run twice

### ISSUE THREAD

**Issue by t0lkman** [johnagan/clean-webpack-plugin#53]
clean-webpack-plugin: C:\Githome\fptigovuinodeweb\client\**\*.* has been removed.
clean-webpack-plugin: C:\Githome\fptigovuinodeweb\client\**\*.* has been removed.

any idea why?

My problem that it deletes js/css files which webpack is creating. So at the end I don't have css/js files in the project. Looks like it cleans files before the webpack run and after

**Comment by johnagan** [comment]
Is this still happening?

**Comment by vineetkumar19871503** [comment]
It is happening with me as well. First of all it removes the build directory then webpack makes a build and then immediately it is removed again.

**Comment by jpgringo** [comment]
@johnagan this is happening to me, also. Was there ever any resolution to this issue?

**Comment by chrisschrijver** [comment]
Have you enabled the "watch" option? 

I Just submitted a pull request which only performs the clean after succesfull compiliation and just before the new files are emitted to the output dir:
https://github.com/johnagan/clean-webpack-plugin/pull/72

**Comment by eballeste** [comment]
this is happening to me, I think it has something to do with using `webpack-dev-server` along with this plugin

**Comment by fqf** [comment]
There was a script in my package.json
`"start": "webpack --config ./configs/dev.webpack.config.js && webpack-dev-server --config ./configs/dev.webpack.config.js"`
Two commands (separated "&&") invoked cleaning two times. In my case case the problem was there.

**Comment by gmartowski** [comment]
> There was a script in my package.json:
> `"start": "webpack --config ./configs/dev.webpack.config.js && webpack-dev-server --config ./configs/dev.webpack.config.js"`
> Two commands (separated "&&") invoked cleaning two times. In my case the problem was there.

I've got exactly the same problem; leaving one ampersand instead of two, fixed problem, @fqf Many thanks !

**Comment by chrisblossom** [comment]
Closed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.
