### ISSUE TITLE
Watch mode deletes all files regardless of changes

### ISSUE THREAD

**Issue by simonsmith** [johnagan/clean-webpack-plugin#54]
Hey,

An issue I've run into is that `watch: true` deletes the entire directory contents each time even if one bundle has changed. As you can imagine this causes a problem with my site trying to load scripts that have now been removed:

Example:
```
- build
--- script1.bundle.234567.js
--- script2.bundle.678987.js
--- script3.bundle.123456.js

// A change causes only `script3.bundle.[chunkhash].js` to be built

- build
--- script3.bundle.432312.js
```

Is it possible for watch mode to hook into the bundles that changed and remove just those?

Edit: I have found that https://github.com/GProst/webpack-clean-obsolete-chunks solves the problem, but the behaviour described does feel like a bug with the way you might expect watch to work.

**Comment by simonsmith** [comment]
@johnagan Did you mean to close this with no response?

**Comment by johnagan** [comment]
Looks like you found a work around. You're also welcome to open a PR if you'd like it in this project.

**Comment by simonsmith** [comment]
It's a workaround, but I think the issue is still valid. It seems to render `watch` somewhat redundant on any larger project.

**Comment by johnagan** [comment]
You're welcome to open a PR if you'd like it in this library, but it's not a use-case I originally built this library for. The description is even "remove/clean your build folder(s)". 

Additionally, it's in pretty bad taste to growth hack this repo for another project.

**Comment by simonsmith** [comment]
> You're welcome to open a PR if you'd like it in this library, but it's not a use-case I originally built this library for. The description is even "remove/clean your build folder(s)".

That's totally fine and I understand your direction for the project. That was all the answer I originally needed.

> Additionally, it's in pretty bad taste to growth hack this repo for another project.

Could you clarify what you mean?

**Comment by johnagan** [comment]
@simonsmith suggesting an alternate package in the body of an issue and expecting to keep it open. It was discussed [here](https://github.com/johnagan/clean-webpack-plugin/issues/43#issuecomment-301773744) already.

**Comment by simonsmith** [comment]
I cannot see how that relates to 'growth hack for another project'. That was merely left as an example of a solution but my main thinking was it's often better to use one plugin than two if possible, particularly if the second one was grown out of a user in the same predicament. 

I'll just carry on as I was. Thanks for your time.
