### ISSUE TITLE
Broken when webpack is called outside of project root

### ISSUE THREAD

**Issue by chrisblossom** [johnagan/clean-webpack-plugin#6]
https://github.com/quangv/clean-webpack-plugin/commit/d32e1b32c8481627c1862627d81193ff621315f4 does not work for paths outside of where webpack.config is called even when specifying root.

``` javascript
// /project/webpack/webpack.config.js
new Clean(['/project/dist/'], '/project/')
// /project/dist/ will not be deleted
```

Here is an example where it would fail.
https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/prod.config.js

I fixed this, as well as added tests, options, and heavily refactored as a result. PR incoming.

**Comment by Ftornik** [comment]
Have the same issue. Pls fix

**Comment by hanjukim** [comment]
+1 Same issue. Please merge PR.

**Comment by samuelmichaud** [comment]
+1 same issue. 
Thanks

**Comment by kilianc** [comment]
+1 on this https://github.com/johnagan/clean-webpack-plugin/blob/master/index.js#L25

**Comment by kilianc** [comment]
Honestly just using `process.cwd()` is fine to me

**Comment by mikestopcontinues** [comment]
+1, `process.cwd()` is an ideal fix.

**Comment by a-tarasyuk** [comment]
+1

**Comment by tonydiaz** [comment]
+1

**Comment by johnagan** [comment]
I merged in #7. Let me know if that helps

**Comment by martinnaughton** [comment]
This worked for me where i have build/webpack.conf.js and dist directory is one level up from the config file. Build and dist directory are in the project root. It gets the absolute path like /home/mart/projectMe/dist/

// the path(s) that should be cleaned
let pathsToClean = [ 
  'dist' 
]

`let cleanOptions = { 
  root:     path.resolve(__dirname, '../'),
  exclude:  [], 
  verbose:  true,
  dry:      false
}
`

**Comment by arkgast** [comment]
I was having the same issue, fixed with `allowExterna: truel`

    new CleanWebpackPlugin(['../public'], {
      root: resolve(__dirname),
      verbose: true,
      allowExternal: true,
    }),
