### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by var-bp** [johnagan/clean-webpack-plugin#61]
Hello, I need to remove all content of `dist` folder except `letters` folder. I have read [#41](https://github.com/johnagan/clean-webpack-plugin/issues/41), but it didn't work for me. With the current settings, the entire content of the folder are deleted.
```
// project structure
my-project
  dist
    assets
    letters
    index.html
  src
```
```
// webpack config
new CleanWebpackPlugin(
  ['dist/*'],
  {
    root: 'my-project', // root works, simplified example
    verbose: true,
    dry: false,
    watch: false,
    exclude: ['letters']
  }
)
```

**Comment by alianrock** [comment]
got the same issue
`new CleanWebpackPlugin(['**/*'], { root: buildPath, exclude: ['lib'] })`

**Comment by zdanowiczkonrad** [comment]
As of `0.1.10` version, this works for me:

```
new CleanPlugin(
    [ production ? 'dist' : 'build' ],
    { exclude: [ 'widget', 'server' ], verbose: true }
);
```
- it properly removes all `dist` and `build` childs excluding `widget` and `server`.

**Comment by johnagan** [comment]
This seems resolved. Please reopen if not

**Comment by captainsalt** [comment]
I'm having the same issue on version `0.1.17`

**Comment by Cheese-Yu** [comment]
I'm having the same issue on version 0.1.17 too!

**Comment by daweilv** [comment]
I'm having the same issue on version 0.1.17 too!

**Comment by Jogai** [comment]
Is it possible to use longer paths for exclusions?

Something like: 
`
new CleanWebpackPlugin(pathsToClean, { exclude: ['child1', 'child2/grandchild'] })
`

**Comment by brybeecher** [comment]
I found that including a wildcard in a path eg.`mypath/*` doesn't work with excludes. Changing to simply `mypath/` worked.

**Comment by InvincibleJun** [comment]
> I found that including a wildcard in a path to clean eg.`mypath/*` doesn't work with excludes. Changing to simply `mypath/` solved the issue for me.
good.

**Comment by Pixelatex** [comment]
> Is it possible to use longer paths for exclusions?
> 
> Something like:
> `new CleanWebpackPlugin(pathsToClean, { exclude: ['child1', 'child2/grandchild'] })`

this, I also want to exclude only a specific nested folder but clear the rest.
