### ISSUE TITLE
Error: EPERM: operation not permitted, mkdir 'c:\***\webpack3-demo\dist'

### ISSUE THREAD

**Issue by liyuhang1997** [johnagan/clean-webpack-plugin#63]
'mkdir' command in windows 

```
c:\Project\wamp\www\webpack3-demo  (webpack3-demo@1.0.0)
λ npm run build
```
```
> webpack3-demo@1.0.0 build c:\Project\wamp\www\webpack3-demo
> webpack

clean-webpack-plugin: C:\Project\wamp\www\webpack3-demo\dist has been removed.
Error: EPERM: operation not permitted, mkdir 'c:\Project\wamp\www\webpack3-demo\dist'
```
I think:  
wrong: ```mkdir 'c:\Project\wamp\www\webpack3-demo\dist'```  
right: ```mkdir c:\Project\wamp\www\webpack3-demo\dist```

**Comment by kvkens** [comment]
自己的权限问题.

**Comment by chrisblossom** [comment]
@liyuhang1997 did you fix your issue? If so, what did you do?

**Comment by liyuhang1997** [comment]
@chrisblossom I did not solve this problem.

**Comment by enzeberg** [comment]
Ensure that no file within `/dist` is being opened in your code editor when you do this operation.

**Comment by hibroseph** [comment]
@endiliey That was my issue in 2020. Thank you.
