### ISSUE TITLE
Remove only when compile is succesful

### ISSUE THREAD

**Issue by valerydev** [johnagan/clean-webpack-plugin#65]
It remove everything at compilation start, but if compilation fails I lost my previous successful compilation

**Comment by jimblue** [comment]
Indeed seems very important to run this plugin after build success and before assets are written.

Actually even if build fail, `clean-webpack-plugin` will delete existing working assets.

This is a big problem as nothing will replace these assets until a build process success.

**Comment by jackypan1989** [comment]
https://github.com/jackypan1989/del-webpack-plugin

**Comment by chrisschrijver** [comment]
Just submitted a pull request to fix this:
https://github.com/johnagan/clean-webpack-plugin/pull/72

**Comment by alexeyvax** [comment]
Hi guys,
were there any changes in this issue.
Did someone add such functionality?

**Comment by ChrisRAoW** [comment]
@alexeyvax My pull request was merged into the core. So you should be able to set the `beforeEmit` to `true`. See documentation: https://github.com/johnagan/clean-webpack-plugin

**Comment by johnagan** [comment]
Thank you @ChrisRAoW 🎉
