### ISSUE TITLE
Add an option to run after instead of just before

### ISSUE THREAD

**Issue by light24bulbs** [johnagan/clean-webpack-plugin#71]
It would be nice to clean up some build files as the very last step as well, not just wait to clean up until the next build is run.  I think there should be a "after:true" option that tells the plugin to use one of the final webpack hooks.  I assume there is a "build complete" hook or something like that.

**Comment by chrisschrijver** [comment]
Just submitted a pull request:
https://github.com/johnagan/clean-webpack-plugin/pull/72
