### ISSUE TITLE
CleanWebpackPlugin does not clean in Webpack 4.0.1

### ISSUE THREAD

**Issue by palaniichukdmytro** [johnagan/clean-webpack-plugin#76]
I am using latest version of webpack 4.0.1 with "clean-webpack-plugin": "^0.1.18" it looks like in this plugin does not clean dist folder when I build.

https://github.com/webpack/webpack/issues/6631

**Comment by atilkan** [comment]
It works actually

**Comment by LouisTakePILLz** [comment]
The plugin is working as intended. It's trying to delete the `dist` folder from the location of the config file (being `webpack/common.js`).

Since you specified your output path to `path.resolve(__dirname, '../dist')`, you should change the root path accordingly (default: `__dirname`):
```js
new CleanWebpackPlugin([ 'dist', 'stats' ], {
  root: path.join(__dirname, '..')
})
```

**Comment by Nataliasem** [comment]
"webpack": "^4.42.0",
"clean-webpack-plugin": "^3.0.0"

In my case it works:

`new CleanWebpackPlugin(
            {
                root: path.join(__dirname, 'dist')
            }
        )`

**Comment by daltonamitchell** [comment]
Looks like `root` isn't supported anymore but I was able to get it working using `cleanOnceBeforeBuildPatterns` like this
```js
new CleanWebpackPlugin({
  cleanOnceBeforeBuildPatterns: [path.join(__dirname, '../dist/**/*')]
})
```

**Comment by AkashicSeer** [comment]
I can't find one single damn good reference for how the hell this plugin even works WTF? Seriously? I can't for the life of me get it to delete anything. The docs are bumpkiss as all hell And it looks like whatever gets it working changes every couple of months. Is there a stable well documented alternative to this or do I have to ROLL MY OWN

**Comment by fsevenm** [comment]
> Looks like `root` isn't supported anymore but I was able to get it working using `cleanOnceBeforeBuildPatterns` like this
> 
> ```js
> new CleanWebpackPlugin({
>   cleanOnceBeforeBuildPatterns: [path.join(__dirname, 'dist/**/*')]
> })
> ```

With `"webpack": "^4.43.0"` and `"clean-webpack-plugin": "^3.0.0"`, only this one works for me.

**Comment by Vanguard90** [comment]
For anyone that stumbled on this thread: It's also a good idea to check what the deletion path is. 

In my case, my app is very, very lean and the build was happening in less than a second. So while I thought files were not getting deleted, they were actually getting deleted and re-generated very quickly.

There is a verbose mode to check which directory CleanWebpackPlugin is looking at. Here is its implementation:

```
new CleanWebpackPlugin({ verbose: true })
```

Otherwise, @Nataliasem, @daltonamitchell  and @fsevenm all gave correct answers to this question.

**Comment by hamzahamidi** [comment]
Honestly how come a simple clean package doesn't work properly ?

**Comment by hamzahamidi** [comment]
The package doesn't work properly with webpack 5 too

**Comment by Clloz** [comment]
It seems that the `output` must have `path` . 

`path: path.join(__dirname, 'dist'),`

It works for me.
