### ISSUE TITLE
Maybe add an option to clean only when file's created date is older than e.g. 30 days.

### ISSUE THREAD

**Issue by joonhocho** [johnagan/clean-webpack-plugin#8]
I think it will be useful when cached pages still requests for older assets.
What are your thoughts?

**Comment by johnagan** [comment]
Personally I'm :-1: on this, but if others feel strongly about it, I'm open to seeing a PR for it

**Comment by hassaans** [comment]
Imagine while a user's on your website and you deploy a new release. And then he moves to a page that used a dynamic import. It won't be able to find that chunk as it does not exist anymore.

**Comment by chrisblossom** [comment]
This is out of scope of this package.

If you are trying to keep old files, you'll need to write previous build assets to disk, then read the asset list and give the list to `cleanOnceBeforeBuildPatterns` / `cleanAfterEveryBuildPatterns` as negative patterns. Is fairly easily accomplished...look into webpack's [done](https://webpack.js.org/api/compiler-hooks/#done) plugin hook. See also: [clean-webpack-plugin.ts#L218-L234](https://github.com/johnagan/clean-webpack-plugin/blob/d6e2e3821fcca8edd9e68ca4cf57198a82e86bb8/src/clean-webpack-plugin.ts#L218-L234)

But then again, you'll have a weird `dev` flow. You probably don't want the old build files in webpack's `output.path` directory.

A better solution than trying to keep a history build manifest would be to just copy all build files into a git-commited directory on release. Then after all cleaning / webpack build, copy the previous assets back to webpack's `output.path`.

IMO, if this is what you are worried about, you should use a CDN and let them handle the caching.
