### ISSUE TITLE
Question: Remove files after emit?

### ISSUE THREAD

**Issue by Legends** [johnagan/clean-webpack-plugin#85]
Is it possible to remove _certain_ files from dist folder after emit?

**Comment by flyyang** [comment]
Try clean-after-emit-webpack-plugin with clean-webpack-plugin.

**Comment by Friksel** [comment]
Thanks for this @flyyang . I installed the clean-after-emit-webpack-plugin and it's working exactly as wanted.
I don't really understand what `beforeEmit: false` on the clean-webpack-plugin is doing then though. I thought if we set `beforeEmit` to `false` that should execute cleaning on the end of emit, but that setting doesn't seem to do anything here. But I might be missing something or doing something wrong.
Anyway, your suggestion works fine, so thanks again!

**Comment by ptrwllrd** [comment]
@Friksel see here for more context: https://github.com/johnagan/clean-webpack-plugin/pull/72#issue-165399571

@flyyang thanks for the handy plugin!

**Comment by chrisblossom** [comment]
Closed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.
