### ISSUE TITLE
Deletes freshly emitted .css files

### ISSUE THREAD

**Issue by angularsen** [johnagan/clean-webpack-plugin#86]
Using `emit` webpack hook seems too late.

I am using `MiniCssExtractPlugin` to emit `.css` files from `.less` files, and my working theory is that this happens before the `emit` hook in webpack is fired. I created my own simple delete plugin that instead uses `compile` hook and what works (see below).

If this plugin either switched to `compile` by default, or had an option to specify what hook to use, then I guess that would also work.

**CustomWebpackDeletePlugin.js**
```js
const fs = require('fs');

function removeDir(path) {
  var execSync = require('child_process').execSync;
  execSync('rm -r ' + path);
  console.log('Deleted: ' + path);
}

function WebpackDeletePlugin(paths) {
  const defaultPaths = [ 'dist'];
  this.paths = paths || defaultPaths;

  if (!this.paths || !this.paths.length) {
    throw '"paths.paths" must be an array with at least one absolute path.';
  }
}

WebpackDeletePlugin.prototype.apply = function(compiler) {
  const paths = this.paths;
  console.log('Params', paths)
  compiler.hooks.compile.tap('Delete files/dirs', (compilation) => {
    for (const path of paths) {
      removeDir(path);
      // fs.unlinkDirSync(path);
      console.log(`Deleted: "${path}"...`)
    }
  });
};

module.exports = WebpackDeletePlugin;
```

**Comment by chrisblossom** [comment]
Closed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.
