### ISSUE TITLE
Will fail if config is not in the same folder as project root.

### ISSUE THREAD

**Issue by IngwiePhoenix** [johnagan/clean-webpack-plugin#9]
I have my project organized in various folders. One of them is `app`. Within there, I have a folder leading to all internal configuration files, including WebPack:

```
app/
  System/
    Config/
      webpack.js
```

Unfortunately, this breaks this plugin. Because the folder I want to delete is on the same level as the app folder - and that is `cdn`, my public assets.

```
app/ ...
cdn/
  app/
    [hash]-[name].(js|css)
```

Adding an option to the plugin to gently force a delete would be nice. I use an automated Surge.sh uploader, and it now uploads _everything_...

**Comment by johnagan** [comment]
Should be fixed in #7
