### ISSUE TITLE
Can't install clean-webpack-plugin

### ISSUE THREAD

**Issue by Flashbackvideoman** [johnagan/clean-webpack-plugin#90]
npm install --save-dev clean-webpack-plugin
produces the following error:

npm ERR! path /home/dovetail/dealware/node_modules/latest/node_modules/npm/node_modules/dezalgo/node_modules/asap
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/dovetail/dealware/node_modules/latest/node_modules/npm/node_modules/dezalgo/node_modules/asap' -> '/home/dovetail/dealware/node_modules/latest/node_modules/npm/node_modules/dezalgo/node_modules/.asap.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Have tried:
Wiping the node_modules directory and npm install
Checking file permissions.

Node version: 8.11.4
NPM version: 5.6.0

**Comment by chrisblossom** [comment]
Closed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.
