### ISSUE TITLE
Partial clean with hash

### ISSUE THREAD

**Issue by patric-eberle** [johnagan/clean-webpack-plugin#91]
I have a case where some unneeded files are created during build which I would like to delete. The files have an unknown hash. How can I delete those? The wildcard `*` seems not to work if I use it as part of the url. e.g. `project/public/Yves/assets/js/shop.theme-01.*.js` is not found, even thought the path and file name is correct. If I replace `*` with the current hash it works. I can not use `*.js` because there are files in the same folder which I want to keep.

Any recommendations?

**Comment by chrisblossom** [comment]
Closed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.
