### ISSUE TITLE
watch option does not work correctly if enabled from webpack CLI

### ISSUE THREAD

**Issue by lcrosetto** [johnagan/clean-webpack-plugin#92]
webpack@4.17.2
clean-webpack-plugin@0.1.19

`options: {beforeEmit: true, watch: false}`

If webpack is run using the `-w` option from the CLI, `compiler.options.watch` is not set. Consequently, if `beforeEmit` is set to true and `watch` is set to false, then the files will still be removed even though watch mode is enabled:

`} else if (_this.options.beforeEmit && !compiler.options.watch) {`

**Comment by meglio** [comment]
Even though my options are:

`options: {beforeEmit: true, watch: true}`

... more files are removed than updated by the rebuild, which ends up in some files missing.

Is this a bug or misconfiguration in my webpack config file?

**Comment by legendar** [comment]
WORKAROUND:

`beforeEmit: process.env.NODE_ENV !== 'development',`

**Comment by chrisblossom** [comment]
Closed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.
