### ISSUE TITLE
when running webpack dev server with clean plugin clearing dist folder and content not served

### ISSUE THREAD

**Issue by saibhargavag** [johnagan/clean-webpack-plugin#96]
hi I am running webpack dev server with clean webpack plug in. It is working fine if we are just building it. but when I start dev server this plugin is clearing dist folder and so there is nothing to serve for the server and my screen is empty.

This is wepack configuratio I used.

plugins: [
       new cleanWebPackOutPut(['dist/*.*']),
        new HtmlWebpackPlugin
        ({
            template: './src/index.html',
            filename: 'index.html',
            hash:true,
            inject: true
        })
      ],
      devServer: {
        index: 'index.html',
        contentBase: path.join(__dirname, 'dist'),
        compress: true,
        hot: true, //Hot module replacement
        port: 9000,
        open: 'chrome' //open in chrome
      }

**Comment by saibhargavag** [comment]
hi I figured it out. webpack dev server causing the recompile and thus invocation of clean webpack plugin, which clears dist folder. but to keep files there in dist folder you must instruct it to write to disk. then after every recompile it writes files to disk this can be set through writeToDisk:true,

devServer: {
index: 'index.html',
contentBase: path.join(__dirname, 'dist'),
compress: true,
hot: true, //Hot module replacement
port: 9000,
writeToDisk:true,
open: 'chrome' //open in chrome
}

this solved my question of keeping output files generated intact.

**Comment by wenxuehai** [comment]
What version of the webpack-dev-server do you use. I have tried, but failed

**Comment by wenxuehai** [comment]
@saibhargavag

**Comment by NageshKuruva** [comment]
thanks it worked for me :)

**Comment by pabloQubit** [comment]
Oh, thank so much

**Comment by ousmanediallo95** [comment]
Thank you dear. it working for me .

**Comment by stepanovmax** [comment]
> hi I figured it out. webpack dev server causing the recompile and thus invocation of clean webpack plugin, which clears dist folder. but to keep files there in dist folder you must instruct it to write to disk. then after every recompile it writes files to disk this can be set through writeToDisk:true,
> 
> devServer: {
> index: 'index.html',
> contentBase: path.join(__dirname, 'dist'),
> compress: true,
> hot: true, //Hot module replacement
> port: 9000,
> writeToDisk:true,
> open: 'chrome' //open in chrome
> }
> 
> this solved my question of keeping output files generated intact.

That's worked for me :)
