### ISSUE TITLE
[Question] beforeEmit not default as true?

### ISSUE THREAD

**Issue by AAllport** [johnagan/clean-webpack-plugin#97]
Hi Dev,

Just a question as to why the beforeEmit option doesn't default to true.
Seems like that would be the logical thing to do?

Great Plugin BTW
AAllport

**Comment by johnagan** [comment]
I agree it would be better to have it as default, though changing it in its current state could break people depending on it not being default. I will definitely change this for future versions though.

**Comment by chrisblossom** [comment]
This has been changed in [`v2.0.0`](https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.0) via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.

**Comment by AAllport** [comment]
Sweet, thanks for the update. Keep up the good work :)

**Comment by oles** [comment]
Awesome that this default got changed! However, it wasn't quite clear for me that this was the case in the 2.0 release notes - perhaps stick it in there, if possible?

Well done @chrisblossom and @johnagan, the defaults should work well for most use cases now - myself included!

**Comment by chrisblossom** [comment]
@oles I've added [Additional v2 Information](https://github.com/johnagan/clean-webpack-plugin/issues/106) to further clarify the changes in `v2`.
