### ISSUE TITLE
Exclude specific sub folders

### ISSUE THREAD

**Issue by Pixelatex** [johnagan/clean-webpack-plugin#98]
I know you can exclude specific folders like this:

` exclude:  ['media'],`

this works if the folder is placed like this:

root
-> media

However, I have a folder like this:

root
-> assets
--> subfolder
---> media

So logic dictates that this exclude should work:

` exclude:  ['assets/subfolder/media'],`

But it doesn't... is there some way I can make this work?

**Comment by chrisblossom** [comment]
Closed via #99. See [johnagan/clean-webpack-plugin#usage](https://github.com/johnagan/clean-webpack-plugin#usage). Please open a new issue if you continue to have problems.
